// Code generated by MockGen. DO NOT EDIT.
// Source: entities/task_service.go

// Package mock_entities is a generated GoMock package.
package mock_entities

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/tonnytg/tasklist/entities"
)

// MockTaskServiceInterface is a mock of TaskServiceInterface interface.
type MockTaskServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceInterfaceMockRecorder
}

// MockTaskServiceInterfaceMockRecorder is the mock recorder for MockTaskServiceInterface.
type MockTaskServiceInterfaceMockRecorder struct {
	mock *MockTaskServiceInterface
}

// NewMockTaskServiceInterface creates a new mock instance.
func NewMockTaskServiceInterface(ctrl *gomock.Controller) *MockTaskServiceInterface {
	mock := &MockTaskServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTaskServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskServiceInterface) EXPECT() *MockTaskServiceInterfaceMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTaskServiceInterface) Create(name, description, body, status string) (entities.TaskInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", name, description, body, status)
	ret0, _ := ret[0].(entities.TaskInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTaskServiceInterfaceMockRecorder) Create(name, description, body, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTaskServiceInterface)(nil).Create), name, description, body, status)
}

// Get mocks base method.
func (m *MockTaskServiceInterface) Get(hash string) (entities.TaskInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", hash)
	ret0, _ := ret[0].(entities.TaskInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockTaskServiceInterfaceMockRecorder) Get(hash interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockTaskServiceInterface)(nil).Get), hash)
}

// Update mocks base method.
func (m *MockTaskServiceInterface) Update(hash, name, description, body, status string) (entities.TaskInterface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", hash, name, description, body, status)
	ret0, _ := ret[0].(entities.TaskInterface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTaskServiceInterfaceMockRecorder) Update(hash, name, description, body, status interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTaskServiceInterface)(nil).Update), hash, name, description, body, status)
}
